import = ["~/.config/alacritty/alacritty-shell.toml"]

live_config_reload = true

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.97
padding = { x = 0, y = 0 }

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Medium Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

# # Colors (Blood Moon)
# # Default colors
[colors.primary]
  background = '#000000'
  foreground = '#C6C6C4'

# Normal colors
[colors.normal]
  black   = '#101020'
  red     = '#C40233'
  green   = '#009F6B'
  yellow  = '#FFD700'
  blue    = '#0087BD'
  magenta = '#9A4EAE'
  cyan    = '#20B2AA'
  white   = '#C6C6C8'

# Bright colors
[colors.bright]
  black   = '#696969'
  red     = '#FF2400'
  green   = '#03C03C'
  yellow  = '#FDFF00'
  blue    = '#007FFF'
  magenta = '#FF1493'
  cyan    = '#00CCCC'
  white   = '#FFFAFA'


  # - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  # - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
  # - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  # - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  # - { key: Back,     mods: Command, chars: "\x15"                        } # Delete line
  # - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    } # Delete word

[[keyboard.bindings]]
  key = "Back"
  mods = "Command"
  chars = "\u0015"

