#!/usr/bin/env sh
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

# global settings
yabai -m config \
	menubar_opacity 1.0 \
	mouse_follows_focus on \
	focus_follows_mouse off \
	display_arrangement_order default \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow on \
	window_animation_easing ease_out_circ \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	bottom_padding 0 \
	left_padding 0 \
	right_padding 0 \
	window_gap 3 \
	layout bsp \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	external_bar all:30:0 \
	mouse_drop_action swap

# bsp or float (default: float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Override gaps for space 2 only
# yabai -m config --space 2 window_gap 0

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Logi Options+" manage=off
yabai -m rule --add app="^Finder" manage=off

echo "$(date) yabai configuration loaded.."
